### ISSUE TITLE
Error config.json

### ISSUE THREAD

**Issue by iron-coder12** [MrAugu/simple-discordjs-dashboard#48]
Hello there @MrAugu ,
I own a bot and I am making a dashboard. I see that your template is exactly what we need. I git cloned it but I am getting this error.
Please respond to this issue as soon as possible.

this is the error I am getting:
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/f/me/Cool/Dashboard/simple-discordjs-dashboard/index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3) ```

Please tell me what should I do to solve this error

Thanks,
Shaurya Rathi

**Comment by Myst82015** [comment]
> 
> 
> Hello there @MrAugu ,
> I own a bot and I am making a dashboard. I see that your template is exactly what we need. I git cloned it but I am getting this error.
> Please respond to this issue as soon as possible.
> 
> this is the error I am getting:
> 
> ```
> internal/modules/cjs/loader.js:638
>     throw err;
>     ^
> 
> Error: Cannot find module './config'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/mnt/f/me/Cool/Dashboard/simple-discordjs-dashboard/index.js:7:16)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3) ```
> 
> Please tell me what should I do to solve this error
> 
> Thanks,
> Shaurya Rathi
> ```

Alright. Did you rename _config.js to config.js after filling out all the values in it?

If you need further assistance please join the support server and make a ticket in the #info channel. 
https://discord.gg/aP9UYfaFa4
